name: "Determine next tag from PR body"
description: "Determine next tag from PR body"

inputs:
  pr_body:
    description: |
      Body of pull request if inside a pull request
    required: false

  pr_number:
    description: |
      Pull request number
    required: false

# Expose step outputs as job outputs
outputs:
  current_tag:
    description: "Current tag version"
    value: ${{ steps.determine_current_tag.outputs.current_tag }}
  new_tag:
    description: "Next tag version"
    value: ${{ steps.determine_next_tag.outputs.new_tag }}

runs:
  using: "composite"

  steps:
    - name: Set GitHub Path
      shell: bash
      env:
        GITHUB_ACTION_PATH: ${{ github.action_path }}
      run: |
        echo "$GITHUB_ACTION_PATH" >> $GITHUB_PATH

    - uses: actions/checkout@v4
    - uses: fregante/setup-git-user@v2

    - name: Determine new tag version from PR event
      if: ${{ inputs.pr_body != '' && inputs.pr_number != '' }}
      shell: sh
      id: determine_next_tag_from_pr_event
      # User controlled input needs to be santitised beforehand e.g., by adding an
      # intermediate env var to prevent the workflow being exposed to a critical
      # command injection attack
      env:
        PR_BODY: "${{ inputs.pr_body }}"
        PR_NUMBER: "${{ inputs.pr_number }}"
      run: |
        echo "Determining whether user has selected an auto-tag option..."
        script_output=$("${{ github.action_path }}/auto-tag.sh" "${PR_BODY}" "${PR_NUMBER}")
        if $? != 0; then
          exit 1
        fi
        new_tag=$(echo "${script_output}" | tail -n 1)
        echo "New tag: ${new_tag}"
        echo "new_tag=${new_tag}"  >> "$GITHUB_OUTPUT"

    - uses: actions/github-script@v7
      if: ${{ (inputs.pr_body == '' && inputs.pr_number == '') }}
      id: get_pr_data
      with:
        script: |
          return (
            await github.rest.repos.listPullRequestsAssociatedWithCommit({
              commit_sha: context.sha,
              owner: context.repo.owner,
              repo: context.repo.repo,
            })
          ).data[0];

    - name: Dump PR body file
      if: ${{ (inputs.pr_body == '' && inputs.pr_number == '') && steps.get_pr_data.outputs.result && (fromJSON(steps.get_pr_data.outputs.result).number && fromJSON(steps.get_pr_data.outputs.result).body) }}
      shell: bash
      env:
        pr_dump_file: "./tmp_pr_body_dump.txt"
      run: |
        echo "Dumping PR body to file..."
        rm -f "${pr_dump_file}"
        touch "${pr_dump_file}"
        pr_body="${{ fromJson(steps.get_pr_data.outputs.result).body }}"
        cat > "${pr_dump_file}" <<EOF
        "${pr_body}"
        EOF
        echo "Cat-ting ${pr_dump_file}..."
        cat "${pr_dump_file}"

    - name: Determine new tag version
      if: ${{ (inputs.pr_body == '' && inputs.pr_number == '') && steps.get_pr_data.outputs.result && (fromJSON(steps.get_pr_data.outputs.result).number && fromJSON(steps.get_pr_data.outputs.result).body) }}
      shell: sh
      env:
        PR_NUMBER: "${{ fromJson(steps.get_pr_data.outputs.result).number }}"
      id: determine_next_tag_retrospectively
      run: |
        echo "Determining whether user selected an auto-tag option..."
        echo "Using GitHub script to get PR info..."
        pr_dump_file="./tmp_pr_body_dump.txt"
        script_output=$("${{ github.action_path }}/auto-tag.sh" "${pr_dump_file}"
        if $? != 0; then
          exit 1
        fi
        new_tag=$(echo "${script_output}" | tail -n 1)
        echo "New tag: ${new_tag}"
        echo "new_tag=${new_tag}"  >> "$GITHUB_OUTPUT"

    - name: Set new_tag
      shell: bash
      id: determine_next_tag
      run: |
        echo "Outputting new tag..."
        if [[ ${{ (inputs.pr_body != '' && inputs.pr_number != '') }} == true ]]; then
            echo "PR body and number present. Using new_tag from 'determine_next_tag_from_pr_event'"
            echo "new_tag=${{ steps.determine_next_tag_from_pr_event.outputs.new_tag }}"  >> "$GITHUB_OUTPUT"
        elif [[ ${{ (inputs.pr_body == '' && inputs.pr_number == '') }} == true ]]; then
            echo "PR body and number not present. Using new_tag from 'determine_next_tag_retrospectively'"
            echo "new_tag=${{ steps.determine_next_tag_retrospectively.outputs.new_tag }}"  >> "$GITHUB_OUTPUT"
        else
            echo "PR body or number present. Either both or neither must be passed."
        fi

    - name: Determine current tag
      id: determine_current_tag
      shell: bash
      run: |
        source "${{ github.action_path }}/funcs.sh"
        current_tag=$(get_latest_tag)
        if [[ -z "${current_tag}" ]]; then
          exit 1;
        else
          echo "Current tag: ${current_tag}"
          echo "current_tag=${current_tag}"  >> "$GITHUB_OUTPUT"
        fi
