name: "Determine next tag from PR body"
description: "Determine next tag from PR body"

inputs:
  pr_body:
    description: |
      Body of pull request if inside a pull request
    required: false
  pr_number:
    description: |
      Pull request number
    required: false
  owner:
    description: |
      Repository Owning Organisation
      Default is 'climatepolicyradar'.
    default: "climatepolicyradar"
    required: false

# Expose step outputs as job outputs
outputs:
  new_tag:
    description: "Next tag version"
    value: ${{ steps.determine_next_tag.outputs.new_tag }}

runs:
  using: "composite"

  steps:
    - name: Debug
      shell: bash
      run: |
        echo ${{ inputs.pr_body }}
        echo ${{ inputs.pr_number }}
        echo ${{ inputs.pr_body == '' && inputs.pr_number == ''}}

    - uses: actions/github-script@v6
      if: ${{ inputs.pr_body == '' && inputs.pr_number == ''}}
      id: get_pr_data
      with:
        script: |
          return (
            await github.rest.repos.listPullRequestsAssociatedWithCommit({
              commit_sha: context.sha,
              owner: context.repo.owner,
              repo: context.repo.repo,
            })
          ).data[0];

    - uses: actions/checkout@v4
    - uses: fregante/setup-git-user@v2

    - name: Determine new tag version from retrospective PR parsing
      if: ${{ inputs.pr_body == '' && inputs.pr_number == ''}}
      shell: sh
      id: determine_next_tag
      # User controlled input needs to be santitised beforehand e.g., by adding an
      # intermediate env var to prevent the workflow being exposed to a critical
      # command injection attack
      env:
        PR_BODY: "${{ fromJson(steps.get_pr_data.outputs.result).body }}"
        PR_NUMBER: "${{ fromJson(steps.get_pr_data.outputs.result).number }}"
      run: |
        echo "Attempting to auto-tag merge commit"
        script_output=$("${{ github.action_path }}/auto-tag.sh" "${PR_BODY}" "${PR_NUMBER}")
        if $? != 0; then
          exit 1
        fi
        new_tag=$(echo "${script_output}" | tail -n 1)
        echo "New tag: ${new_tag}"
        echo "new_tag=${new_tag}"  >> "$GITHUB_OUTPUT"

    - name: Determine new tag version from PR event
      if: ${{ inputs.pr_body != '' && inputs.pr_number != ''}}
      shell: sh
      id: determine_next_tag_from_pr_event
      # User controlled input needs to be santitised beforehand e.g., by adding an
      # intermediate env var to prevent the workflow being exposed to a critical
      # command injection attack
      env:
        PR_BODY: ${{ inputs.pr_body }}
        PR_NUMBER: ${{ inputs.pr_number }}
      run: |
        echo "Attempting to auto-tag merge commit"
        script_output=$("${{ github.action_path }}/auto-tag.sh" "${PR_BODY}" "${PR_NUMBER}")
        if $? != 0; then
          exit 1
        fi
        new_tag=$(echo "${script_output}" | tail -n 1)
        echo "New tag: ${new_tag}"
        echo "new_tag=${new_tag}"  >> "$GITHUB_OUTPUT"
