name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Test bash scripts
        run: make test_bashscripts

  dependabot:
    name: Dependabot Auto-pilot
    if: github.event_name == 'pull_request'
    needs: [test]
    permissions:
      pull-requests: write
      contents: write
    uses: climatepolicyradar/reusable-workflows/.github/workflows/dependabot-autopilot.yml@v23
    with:
      auto-approve: false
